
use_frameworks!

platform :ios, '9.0'


flutter_application_path = '../ExampleModule'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Zind_Example' do
  pod 'Zind', :path => '../'
	install_all_flutter_pods(flutter_application_path)
end
