//
//  ZindRouteModel.h
//  Zind
//
//  Created by lzackx on 2021/3/24.
//

// Generated by https://quicktype.io

#import <Foundation/Foundation.h>
#import <YYModel/YYModel.h>

@class ZindRouteModel;
@class ZindParameters;
@class ZindPublic;


NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, ZindRouteModelRouterType) {
	ZindRouteModelRouterTypeGeneral,
	ZindRouteModelRouterTypeShared,
	ZindRouteModelRouterTypePopUp,
	ZindRouteModelRouterTypeStack,
};

FOUNDATION_EXPORT const NSString * const ZindDefaultRouteModelString;

@interface ZindRouteModel : NSObject
@property (nonatomic, copy)   NSString *url;
@property (nonatomic, strong) ZindParameters *parameters;
@end

@interface ZindParameters : NSObject
@property (nonatomic, strong) ZindPublic *public;
@property (nonatomic, copy) NSDictionary *private;
@end

@interface ZindPublic : NSObject
@property (nonatomic, strong) NSNumber *routerType;
@property (nonatomic, copy)   NSString *app;
@property (nonatomic, strong) NSNumber *environment;
@property (nonatomic, copy)   NSString *muid;
@property (nonatomic, copy)   NSString *platform;
@property (nonatomic, strong) NSNumber *safeareaTop;
@property (nonatomic, strong) NSNumber *safeareaBottom;
@property (nonatomic, copy)   NSString *version;
@property (nonatomic, copy)   NSString *systemVersion;
@property (nonatomic, copy)   NSString *ua;
@end

NS_ASSUME_NONNULL_END
